### ISSUE TITLE
Doubt regarding DatabaseInitializer.cs 

### ISSUE THREAD

**Issue by BernardoMeine** [m-jovanovic/outbox-scaling#1]
I just wanted to know if by using raw SQL to initialize the database it could lead to a syntax error, since most IDEs can't detect raw SQL mispells.

@m-jovanovic

**Comment by m-jovanovic** [comment]
Obviously yes. But I assume you'd validate the SQL first before hardcoding it. This is just a quick demo I patched up to get up and running quickly. You're welcome to implement DB migrations using your preferred approach.
